### ISSUE TITLE
System tray icon backgrounds not refreshing

### ISSUE THREAD

**Issue by siphomateke** [solus-project/budgie-desktop#1249]
**Operating System**: e.g. Solus 3.26.2
**Budgie version**: i.e. Budgie 10.4

**The issue encountered**

The system tray icons' backgrounds bug out. They show what was previously there as if the panel is not refreshing. This often means a black background or border. If a new application opens and appears in the system tray it's background seems to be the adjacent icon. It's easier to show this behaviour with screenshots:

On startup
![startup](https://user-images.githubusercontent.com/19307714/32833439-9562c56e-ca07-11e7-9983-6074235ad14c.png)

Moving the system tray to the centre doesn't fix the problem but makes it worse
![centre](https://user-images.githubusercontent.com/19307714/32833498-bcdaf0c6-ca07-11e7-8052-94579d593a6c.png)

If the panel is set to transparent and intelligent automatic hiding, some icons persist after the panel is hidden
![transparent](https://user-images.githubusercontent.com/19307714/32833530-d6153eac-ca07-11e7-9e5f-0f0427f0fc0c.png)

Built in theme on
![built in theme on](https://user-images.githubusercontent.com/19307714/32833554-e9b283e8-ca07-11e7-97b2-3ae3ff4a28b8.png)

Built in theme off
![built in theme off](https://user-images.githubusercontent.com/19307714/32833576-f5110138-ca07-11e7-88a8-1d3062862e4c.png)

Possibly related, the shutdown and restart dialogs have a strange border around them:
![restart](https://user-images.githubusercontent.com/19307714/32833786-c7491b2c-ca08-11e7-8d28-ee4414e6cb13.png)
![shutdown](https://user-images.githubusercontent.com/19307714/32833787-c7867db4-ca08-11e7-8c02-64bbe73dd761.png)

Another thing that might be related is the clock applet is not updating. It seems all sorts of components of the budgie-panel are just not refreshing properly.

**Steps to reproduce the issue**

Happens consistently every time I start up solus. Running `budgie-panel --replace` fixes some icons until next restart. Never used to happen so I am not entirely sure how to reproduce it exactly.

**Comment by tista500** [comment]
Both Fig 5 and 6 look like something fault with OpenGL compositor (Mutter). So ti might be better adding some GPU and driver info... Just my thoughts.

Regards.

**Comment by nextgensparx** [comment]
I found out that the clock applet not updating was purely my fault. I created an applet that shows network statistics and it seems to interfere with the clock applet.

I tried creating a new user to see if any of these issues and persisted and they didn't! So I have now moved everything over to a new user and deleted the old one.

@tista500 What kind of info and where can I find it? Since I deleted my old user I can no longer test but I can provide my specs.

**Comment by tista500** [comment]
> What kind of info and where can I find it?

`inxi -G` might be enough...

Then I'm a bit confused that captured GtkWindows were properly composited by budgie-wm, but budgie-session-dialogs were not. I don't have any clue. Anything happens in budgie-daemon and/or budgie-wm?

**Comment by nextgensparx** [comment]
```
Graphics:  Card: Intel Haswell-ULT Integrated Graphics Controller
           Display Server: x11 (X.Org 1.18.4 )
           drivers: modesetting (unloaded: fbdev,vesa)
           Resolution: 1366x768@59.99hz
           OpenGL: renderer: Mesa DRI Intel Haswell Mobile
           version: 4.5 Mesa 17.2.4
```

Unfortunately, I was pretty frustrated and have deleted the user where these bugs were occurring. As such, I can't test budgie-daemon or budgie-wm. I will report back here if the issues start again.

**Comment by clumsyfingers** [comment]
i had the same problem as reported here https://www.reddit.com/r/SolusProject/comments/7k9ukf/garbled_icons_strange_borders_after_todays_update/

deleting  ~/.local/share/applications/budgie-wm.desktop fixed it

in case someone else has this problem

**Comment by fossfreedom** [comment]
@clumsyfingers that's very odd - why did you have a local budgie-wm.desktop file ?

**Comment by nextgensparx** [comment]
@clumsyfingers I seem to have started having the icon issues again and I don't have a local budgie-wm.desktop file.

**Comment by clumsyfingers** [comment]
@fossfreedom no idea. checking my backup disk the file is dated 3.sept, and even existed in my solus gnome backup dir as well as in the budgie backup dir. i have a vague recollection of installing budgie over solus gnome perhaps around that time, maybe it got created then? 
my current solus budgie installation is newer than that though, i guess ive just copied over the dir, as ive got some custom desktop files there that i like to keep

weird that it should be there all this time and not cause and problems until this weekend though.

@nextgensparx hmm, my temporary fix for the icon problem was to add a script that ran at startup basically looking sometihng like:
sleep 2s
budgie-panel --replace &

**Comment by nextgensparx** [comment]
@clumsyfingers Running `budgie-panel --replace &` only fixes some icons on my end.

This issue has only partially come back. The shutdown and restart dialogs are ok now.

Here are some screenshots:
![img1](https://user-images.githubusercontent.com/19307714/34111213-c5f1abb8-e411-11e7-96c4-0511e830040b.png)
After running `budgie-panel --replace &`:
![img2](https://user-images.githubusercontent.com/19307714/34111211-c5aaef5c-e411-11e7-894f-defc7abbc056.png)

**Comment by clumsyfingers** [comment]
@nextgensparx 
maybe its only related to that particular app's tray icon? have you tried some other apps that have tray icons and see if the problem occurs with them too? for example clipit or thunderbird with firetray?

**Comment by nextgensparx** [comment]
@clumsyfingers I have tried it with other icons and it seems to be Dropbox's icon that gets messed up the most. Other icons just show up with odd black backgrounds. Dropbox's icon buginess also seems to spread to it's neighbours. Really strange.

**Comment by tarek-nawara** [comment]
I guess I have the same problem. with the wifi icon. I start my machine. then suspend then open again and it looks like this
![icons](https://user-images.githubusercontent.com/19335185/34640266-10d2629a-f2f8-11e7-9d95-004fb610a298.png)

**Comment by Mirza101** [comment]
Same here :-\

I've tried disabling notifications as well as changing icon theme to see if it would change anything. It seems to just pile one icon on top of another though.

![screenshot from 2018-01-14 15-02-42](https://user-images.githubusercontent.com/19920323/34920149-0bab7532-f93c-11e7-84a2-7ef9737af4f6.png)

**Comment by paulochf** [comment]
> nextgensparx said:
> I seem to have started having the icon issues again and I don't have a local budgie-wm.desktop file.

[2]

I can say that 95% of the time this bug happens and I don't know why.

**Comment by paulochf** [comment]
Update: when I boot and do the first login, icons bug.

After a `CTRL + Backspace`, I log in and the icons get fixed as they should.

**Comment by theryecatcher** [comment]
Hey Hi, Is this issue resolved because I have been having the same now for quite a few weeks now. I have tried all the things mentioned here. I don't have a ~/.local/share/applications/budgie-wm.desktop file. I created a new user but within few weeks the problem occurred again. I can do `budgie-panel --replace &` and it fixes the system the rest of the app indicators still have the backgrounds on them. Moreover I think it has to do with indicators of applications based on Qt.

![screenshot from 2018-02-11 09 28 20](https://user-images.githubusercontent.com/16442416/36074501-8931e738-0f0e-11e8-9998-cd6a4083164b.png)

**Comment by nextgensparx** [comment]
@theryecatcher No, the issue is not resolved, at least not for me.

**Comment by bertof** [comment]
I have exactly the same problem on a fresh Arch Linux installation. I can share logs if it's useful.

**Comment by fossfreedom** [comment]
ok folks - no need to say "it affects me" - we get it - there is an issue that needs resolving.

I'm wondering - if anyone can say if this is the wrong area to look in - for the system tray in Unity (which is using the same Na component in budgie) https://github.com/GGleb/indicator-systemtray-unity/blob/master/na-tray.c

For the box the draw signal is being connected (line 566) - and each of the children of that box is looked at from a compositing POV - if it recognises an icon has an alpha channel then it manually draws that icon (line 517).  

As I said - maybe I'm reading this wrong and putting 2+2=5 - but possibly the black icon surrounds that we are seeing is because the icon needs to be manually painted.

**Comment by AlienTux** [comment]
Happens to me too. Semi-work around I found was to open Budgie Settings and in the Panel Settings move the panel to bottom (or wherever really). This fixes all icons and I can return my panel to top position.

**Comment by serebit** [comment]
The above commit (3a507d3) seems to have actually caused my system tray to acquire the issue.

**Comment by fossfreedom** [comment]
I have a tentative fix for this. Currently testing. Will PR it soon hopefully.

**Comment by JoshStrobl** [comment]
> 
> 
> The above commit ([3a507d3](https://github.com/solus-project/budgie-desktop/commit/3a507d3bbb6911006520bcc4f3d732aaecdc903a)) seems to have actually caused my system tray to acquire the issue.

No, it already had this issue. Which is why I made the commit in the first place, it didn't resolve it, which is why I didn't close the task.

**Comment by serebit** [comment]
> No, it already had this issue. Which is why I made the commit in the first place, it didn't resolve it, which is why I didn't close the task.

I'm not sure you're understanding me. I did not have this issue, and then I updated Budgie to the above commit, and now my system tray is acting in the manner described in this issue. I'm not saying the issue didn't exist before now, I'm saying it didn't affect me until now.

**Comment by JoshStrobl** [comment]
> 
> 
> > No, it already had this issue. Which is why I made the commit in the first place, it didn't resolve it, which is why I didn't close the task.
> 
> I'm not sure you're understanding me. I did not have this issue, and then I updated Budgie to the above commit, and now my system tray is acting in the manner described in this issue. I'm not saying the issue didn't exist before now, I'm saying it didn't affect me until now.

It started to become more prevalent when I updated Solus to the GNOME 3.34 stack and that is likely the same case for other distributions. My commit has nothing to do with it, it happened after the issue started becoming more prevalent, you'll still have the same issue even if you revert my commit. It doesn't necessarily happen at boot, but it will after multiple various application with tray icons are opened / closed (e.g. opening Discord and QOwnNotes with system tray enabled, while having nm-applet open).

So cool, you didn't have the issue. That doesn't change the fact it still exists.

**Comment by serebit** [comment]
Thank you for the explanation, although the addendum wasn't really called for considering I didn't attempt to invalidate the existence of this issue in the first place.

**Comment by JoshStrobl** [comment]
@fossfreedom Looking forward to the PR. If I get the time next week, I'll be looking into replacing it (or providing an alternative) with AppIndicator support in the Budgie 10.5 series. Aside from that I'm testing an OSD update to account for g-s-d 3.34 int32 -> double changes (e.g. volume) so you can expect that in the pipeline in the next few days.

**Comment by JoshStrobl** [comment]
Validated issue is resolved with this PR. I'll be pushing this out to Solus users on the unstable repo for further validation via https://dev.getsol.us/T8366 and have a call to action for those to reply here, so we can maintain a centralized place to validate the fix before this is marked as resolved.

**Comment by Staudey** [comment]
Unfortunately this doesn't resolve the issue for me. After a reboot I launched Hexchat, Steam and Riot (all of which have tray icons) and got this as a result:
![Screenshot from 2019-09-30 21:07:47](https://user-images.githubusercontent.com/6317346/65908982-d3079f80-e3c7-11e9-8468-8b4328a3492e.png)


Budgie version: `budgie-desktop 10.5 (git-a023c7781435d71e463184124a5cc8b26985d961)`

**Comment by fossfreedom** [comment]
damn

**Comment by JoshStrobl** [comment]
@Staudey Meanwhile here, launching Hexchat, Steam, then Riot (in that order) works :man_shrugging: 

![Screenshot from 2019-09-30 22-20-16](https://user-images.githubusercontent.com/156574/65909150-9f7d4300-e3d0-11e9-9825-9e6726659d6d.png)

**Comment by Staudey** [comment]
I'll take another look at it later tonight or tomorrow. I think the order
in my case was Riot -> Hexchat -> Steam, right after boot (I also tried it
after a second boot, same result). Currently on Windows again, will test
more later.

**Comment by serebit** [comment]
This PR fixes the redraw issue for me, albeit with some odd behavior that I haven't determined to be directly related to the PR.

**Comment by serebit** [comment]
When I update Budgie, and *only* Budgie, the redraw issue resolves-- but only one of the two applets I have configured to launch on login appears in my system tray. The other doesn't seem to be there at all, as in I can't click on it or see it, but the process is launched (I can see it in System Monitor). Not sure if it's related to the PR though.

**Comment by fossfreedom** [comment]
@JoshStrobl I haven't looked in detail with the changes - but gnome-shell's na-tray code is more up-to-date that budgie's.  Significant?

https://github.com/GNOME/gnome-shell/tree/master/src/tray

vs 

https://github.com/solus-project/budgie-desktop/tree/master/src/imports/natray

The diff is the following:

```
diff --git a/src/imports/natray/na-tray-child.c b/src/imports/natray/na-tray-child.c
index f90c4e71..944c7994 100644
--- a/src/imports/natray/na-tray-child.c
+++ b/src/imports/natray/na-tray-child.c
@@ -52,8 +52,9 @@ na_tray_child_realize (GtkWidget *widget)
 
       /* Set a transparent background */
       cairo_pattern_t *transparent = cairo_pattern_create_rgba (0, 0, 0, 0);
+G_GNUC_BEGIN_IGNORE_DEPRECATIONS
       gdk_window_set_background_pattern (window, transparent);
-      gdk_window_set_composited (window, TRUE);
+G_GNUC_END_IGNORE_DEPRECATIONS
       cairo_pattern_destroy (transparent);
 
       child->parent_relative_bg = FALSE;
@@ -62,7 +63,9 @@ na_tray_child_realize (GtkWidget *widget)
     {
       /* Otherwise, if the visual matches the visual of the parent window, we
        * can use a parent-relative background and fake transparency. */
+G_GNUC_BEGIN_IGNORE_DEPRECATIONS
       gdk_window_set_background_pattern (window, NULL);
+G_GNUC_END_IGNORE_DEPRECATIONS
 
       child->parent_relative_bg = TRUE;
     }
@@ -72,17 +75,19 @@ na_tray_child_realize (GtkWidget *widget)
       child->parent_relative_bg = FALSE;
     }
 
-  gdk_window_set_composited (window, child->composited);
-
   gtk_widget_set_app_paintable (GTK_WIDGET (child),
                                 child->parent_relative_bg || child->has_alpha);
 
   /* Double-buffering will interfere with the parent-relative-background fake
    * transparency, since the double-buffer code doesn't know how to fill in the
    * background of the double-buffer correctly.
+   * The function is deprecated because it is only meaningful on X11 - the
+   * same is true for XEmbed of course, so just ignore the warning.
    */
+G_GNUC_BEGIN_IGNORE_DEPRECATIONS
   gtk_widget_set_double_buffered (GTK_WIDGET (child),
                                   child->parent_relative_bg);
+G_GNUC_END_IGNORE_DEPRECATIONS
 }
 
 static void
@@ -95,37 +100,34 @@ na_tray_child_style_set (GtkWidget *widget,
    */
 }
 
+#if 0
+/* This is adapted from code that was commented out in na-tray-manager.c; the
+ * code in na-tray-manager.c wouldn't have worked reliably, this will. So maybe
+ * it can be reenabled. On other hand, things seem to be working fine without
+ * it.
+ *
+ * If reenabling, you need to hook it up in na_tray_child_class_init().
+ */
 static void
-na_tray_child_get_preferred_width (GtkWidget *widget,
-                                   gint      *minimal_width,
-                                   gint      *natural_width)
-{
-  GTK_WIDGET_CLASS (na_tray_child_parent_class)->get_preferred_width (widget,
-                                                                      minimal_width,
-                                                                      natural_width);
-
-  if (*minimal_width < 22)
-    *minimal_width = 22;
-
-  if (*natural_width < 22)
-    *natural_width = 22;
-}
-
-static void
-na_tray_child_get_preferred_height (GtkWidget *widget,
-                                    gint      *minimal_height,
-                                    gint      *natural_height)
+na_tray_child_size_request (GtkWidget      *widget,
+                            GtkRequisition *request)
 {
-  GTK_WIDGET_CLASS (na_tray_child_parent_class)->get_preferred_height (widget,
-                                                                       minimal_height,
-                                                                       natural_height);
+  GTK_WIDGET_CLASS (na_tray_child_parent_class)->size_request (widget, request);
 
-  if (*minimal_height < 22)
-    *minimal_height = 22;
-
-  if (*natural_height < 22)
-    *natural_height = 22;
+  /*
+   * Make sure the icons have a meaningful size ..
+   */ 
+  if ((request->width < 16) || (request->height < 16))
+    {
+      gint nw = MAX (24, request->width);
+      gint nh = MAX (24, request->height);
+      g_warning ("Tray icon has requested a size of (%ix%i), resizing to (%ix%i)", 
+                 req.width, req.height, nw, nh);
+      request->width = nw;
+      request->height = nh;
+    }
 }
+#endif
 
 static void
 na_tray_child_size_allocate (GtkWidget      *widget,
@@ -235,8 +237,6 @@ na_tray_child_class_init (NaTrayChildClass *klass)
   gobject_class->finalize = na_tray_child_finalize;
   widget_class->style_set = na_tray_child_style_set;
   widget_class->realize = na_tray_child_realize;
-  widget_class->get_preferred_width = na_tray_child_get_preferred_width;
-  widget_class->get_preferred_height = na_tray_child_get_preferred_height;
   widget_class->size_allocate = na_tray_child_size_allocate;
   widget_class->draw = na_tray_child_draw;
 }
@@ -246,6 +246,7 @@ na_tray_child_new (GdkScreen *screen,
                    Window     icon_window)
 {
   XWindowAttributes window_attributes;
+  GdkDisplay *display;
   Display *xdisplay;
   NaTrayChild *child;
   GdkVisual *visual;
@@ -257,15 +258,16 @@ na_tray_child_new (GdkScreen *screen,
   g_return_val_if_fail (icon_window != None, NULL);
 
   xdisplay = GDK_SCREEN_XDISPLAY (screen);
+  display = gdk_x11_lookup_xdisplay (xdisplay);
 
   /* We need to determine the visual of the window we are embedding and create
    * the socket in the same visual.
    */
 
-  gdk_error_trap_push ();
+  gdk_x11_display_error_trap_push (display);
   result = XGetWindowAttributes (xdisplay, icon_window,
                                  &window_attributes);
-  gdk_error_trap_pop_ignored ();
+  gdk_x11_display_error_trap_pop_ignored (display);
 
   if (!result) /* Window already gone */
     return NULL;
@@ -288,9 +290,7 @@ na_tray_child_new (GdkScreen *screen,
   depth = gdk_visual_get_depth (visual);
 
   visual_has_alpha = red_prec + blue_prec + green_prec < depth;
-  child->has_alpha = (visual_has_alpha && gdk_screen_is_composited (screen));
-
-  child->composited = child->has_alpha;
+  child->has_alpha = visual_has_alpha;
 
   return GTK_WIDGET (child);
 }
@@ -314,7 +314,7 @@ na_tray_child_get_title (NaTrayChild *child)
   utf8_string = gdk_x11_get_xatom_by_name_for_display (display, "UTF8_STRING");
   atom = gdk_x11_get_xatom_by_name_for_display (display, "_NET_WM_NAME");
 
-  gdk_error_trap_push ();
+  gdk_x11_display_error_trap_push (display);
 
   result = XGetWindowProperty (GDK_DISPLAY_XDISPLAY (display),
                                child->icon_window,
@@ -323,8 +323,8 @@ na_tray_child_get_title (NaTrayChild *child)
                                False, utf8_string,
                                &type, &format, &nitems,
                                &bytes_after, (guchar **)&val);
-
-  if (gdk_error_trap_pop () || result != Success)
+  
+  if (gdk_x11_display_error_trap_pop (display) || result != Success)
     return NULL;
 
   if (type != utf8_string ||
@@ -367,33 +367,6 @@ na_tray_child_has_alpha (NaTrayChild *child)
   return child->has_alpha;
 }
 
-/**
- * na_tray_child_set_composited;
- * @child: a #NaTrayChild
- * @composited: %TRUE if the child's window should be redirected
- *
- * Sets whether the #GdkWindow of the child should be set redirected
- * using gdk_window_set_composited(). By default this is based off of
- * na_tray_child_has_alpha(), but it may be useful to override it in
- * certain circumstances; for example, if the #NaTrayChild is added
- * to a parent window and that parent window is composited against the
- * background.
- */
-void
-na_tray_child_set_composited (NaTrayChild *child,
-                              gboolean     composited)
-{
-  g_return_if_fail (NA_IS_TRAY_CHILD (child));
-
-  if (child->composited == composited)
-    return;
-
-  child->composited = composited;
-  if (gtk_widget_get_realized (GTK_WIDGET (child)))
-    gdk_window_set_composited (gtk_widget_get_window (GTK_WIDGET (child)),
-                               composited);
-}
-
 /* If we are faking transparency with a window-relative background, force a
  * redraw of the icon. This should be called if the background changes or if
  * the child is shifted with respect to the background.
@@ -410,7 +383,8 @@ na_tray_child_force_redraw (NaTrayChild *child)
        * icon is expecting the server to clear-to-background before
        * the redraw. It should be ok for GtkStatusIcon or EggTrayIcon.
        */
-      Display *xdisplay = GDK_DISPLAY_XDISPLAY (gtk_widget_get_display (widget));
+      GdkDisplay *display = gtk_widget_get_display (widget);
+      Display *xdisplay = GDK_DISPLAY_XDISPLAY (display);
       XEvent xev;
       GdkWindow *plug_window;
       GtkAllocation allocation;
@@ -426,12 +400,12 @@ na_tray_child_force_redraw (NaTrayChild *child)
       xev.xexpose.height = allocation.height;
       xev.xexpose.count = 0;
 
-      gdk_error_trap_push ();
+      gdk_x11_display_error_trap_push (display);
       XSendEvent (xdisplay,
                   xev.xexpose.window,
                   False, ExposureMask,
                   &xev);
-      gdk_error_trap_pop_ignored ();
+      gdk_x11_display_error_trap_pop_ignored (display);
 #else
       /* Hiding and showing is the safe way to do it, but can result in more
        * flickering.
@@ -468,14 +442,16 @@ _get_wmclass (Display *xdisplay,
               char   **res_class,
               char   **res_name)
 {
+  GdkDisplay *display;
   XClassHint ch;
 
   ch.res_name = NULL;
   ch.res_class = NULL;
 
-  gdk_error_trap_push ();
+  display = gdk_x11_lookup_xdisplay (xdisplay);
+  gdk_x11_display_error_trap_push (display);
   XGetClassHint (xdisplay, xwindow, &ch);
-  gdk_error_trap_pop_ignored ();
+  gdk_x11_display_error_trap_pop_ignored (display);
 
   if (res_class)
     *res_class = NULL;
diff --git a/src/imports/natray/na-tray-child.h b/src/imports/natray/na-tray-child.h
index eb4434f2..d1436764 100644
--- a/src/imports/natray/na-tray-child.h
+++ b/src/imports/natray/na-tray-child.h
@@ -42,7 +42,6 @@ struct _NaTrayChild
   GtkSocket parent_instance;
   Window icon_window;
   guint has_alpha : 1;
-  guint composited : 1;
   guint parent_relative_bg : 1;
 };
 
@@ -57,8 +56,6 @@ GtkWidget      *na_tray_child_new            (GdkScreen    *screen,
                                               Window        icon_window);
 char           *na_tray_child_get_title      (NaTrayChild  *child);
 gboolean        na_tray_child_has_alpha      (NaTrayChild  *child);
-void            na_tray_child_set_composited (NaTrayChild  *child,
-                                              gboolean      composited);
 void            na_tray_child_force_redraw   (NaTrayChild  *child);
 void            na_tray_child_get_wm_class   (NaTrayChild  *child,
 					      char        **res_name,
diff --git a/src/imports/natray/na-tray-manager.c b/src/imports/natray/na-tray-manager.c
index 58b91b56..15e1d80e 100644
--- a/src/imports/natray/na-tray-manager.c
+++ b/src/imports/natray/na-tray-manager.c
@@ -24,8 +24,12 @@
 
 #include "na-tray-manager.h"
 
+#if defined (GDK_WINDOWING_X11)
 #include <gdk/gdkx.h>
 #include <X11/Xatom.h>
+#elif defined (GDK_WINDOWING_WIN32)
+#include <gdk/gdkwin32.h>
+#endif
 #include <gtk/gtk.h>
 
 /* Signals */
@@ -48,7 +52,7 @@ typedef struct
 {
   long id, len;
   long remaining_len;
-
+  
   long timeout;
   char *str;
 #ifdef GDK_WINDOWING_X11
@@ -66,7 +70,7 @@ static guint manager_signals[LAST_SIGNAL];
 #define SYSTEM_TRAY_ORIENTATION_VERT 1
 
 #ifdef GDK_WINDOWING_X11
-static gboolean na_tray_manager_check_running_screen_x11 (GdkScreen *screen);
+static gboolean na_tray_manager_check_running_screen_x11 (void);
 #endif
 
 static void na_tray_manager_finalize     (GObject      *object);
@@ -89,35 +93,28 @@ na_tray_manager_init (NaTrayManager *manager)
   manager->invisible = NULL;
   manager->socket_table = g_hash_table_new (NULL, NULL);
 
-  manager->padding = 0;
-  manager->icon_size = 0;
-
-  manager->fg.red = 0.0;
-  manager->fg.green = 0.0;
-  manager->fg.blue = 0.0;
-  manager->fg.alpha = 1.0;
+  manager->fg.red = 0;
+  manager->fg.green = 0;
+  manager->fg.blue = 0;
 
-  manager->error.red = 1.0;
-  manager->error.green = 0.0;
-  manager->error.blue = 0.0;
-  manager->error.alpha = 1.0;
+  manager->error.red = 0xff;
+  manager->error.green = 0;
+  manager->error.blue = 0;
 
-  manager->warning.red = 1.0;
-  manager->warning.green = 1.0;
-  manager->warning.blue = 0.0;
-  manager->warning.alpha = 1.0;
+  manager->warning.red = 0xff;
+  manager->warning.green = 0xff;
+  manager->warning.blue = 0;
 
-  manager->success.red = 0.0;
-  manager->success.green = 1.0;
-  manager->success.blue = 0.0;
-  manager->success.alpha = 1.0;
+  manager->success.red = 0;
+  manager->success.green = 0xff;
+  manager->success.blue = 0;
 }
 
 static void
 na_tray_manager_class_init (NaTrayManagerClass *klass)
 {
   GObjectClass *gobject_class;
-
+  
   gobject_class = (GObjectClass *)klass;
 
   gobject_class->finalize = na_tray_manager_finalize;
@@ -132,17 +129,15 @@ na_tray_manager_class_init (NaTrayManagerClass *klass)
 						      GTK_TYPE_ORIENTATION,
 						      GTK_ORIENTATION_HORIZONTAL,
 						      G_PARAM_READWRITE |
-						      G_PARAM_CONSTRUCT |
-						      G_PARAM_STATIC_NAME |
-						      G_PARAM_STATIC_NICK |
-						      G_PARAM_STATIC_BLURB));
-
+						      G_PARAM_STATIC_STRINGS |
+						      G_PARAM_CONSTRUCT));
+  
   manager_signals[TRAY_ICON_ADDED] =
     g_signal_new ("tray_icon_added",
 		  G_OBJECT_CLASS_TYPE (klass),
 		  G_SIGNAL_RUN_LAST,
 		  G_STRUCT_OFFSET (NaTrayManagerClass, tray_icon_added),
-		  NULL, NULL, NULL,
+                  NULL, NULL, NULL,
 		  G_TYPE_NONE, 1,
 		  GTK_TYPE_SOCKET);
 
@@ -151,7 +146,7 @@ na_tray_manager_class_init (NaTrayManagerClass *klass)
 		  G_OBJECT_CLASS_TYPE (klass),
 		  G_SIGNAL_RUN_LAST,
 		  G_STRUCT_OFFSET (NaTrayManagerClass, tray_icon_removed),
-		  NULL, NULL, NULL,
+                  NULL, NULL, NULL,
 		  G_TYPE_NONE, 1,
 		  GTK_TYPE_SOCKET);
   manager_signals[MESSAGE_SENT] =
@@ -159,7 +154,7 @@ na_tray_manager_class_init (NaTrayManagerClass *klass)
 		  G_OBJECT_CLASS_TYPE (klass),
 		  G_SIGNAL_RUN_LAST,
 		  G_STRUCT_OFFSET (NaTrayManagerClass, message_sent),
-		  NULL, NULL, NULL,
+                  NULL, NULL, NULL,
 		  G_TYPE_NONE, 4,
 		  GTK_TYPE_SOCKET,
 		  G_TYPE_STRING,
@@ -170,7 +165,7 @@ na_tray_manager_class_init (NaTrayManagerClass *klass)
 		  G_OBJECT_CLASS_TYPE (klass),
 		  G_SIGNAL_RUN_LAST,
 		  G_STRUCT_OFFSET (NaTrayManagerClass, message_cancelled),
-		  NULL, NULL, NULL,
+                  NULL, NULL, NULL,
 		  G_TYPE_NONE, 2,
 		  GTK_TYPE_SOCKET,
 		  G_TYPE_LONG);
@@ -179,7 +174,7 @@ na_tray_manager_class_init (NaTrayManagerClass *klass)
 		  G_OBJECT_CLASS_TYPE (klass),
 		  G_SIGNAL_RUN_LAST,
 		  G_STRUCT_OFFSET (NaTrayManagerClass, lost_selection),
-		  NULL, NULL, NULL,
+                  NULL, NULL, NULL,
 		  G_TYPE_NONE, 0);
 
 #if defined (GDK_WINDOWING_X11)
@@ -195,14 +190,14 @@ static void
 na_tray_manager_finalize (GObject *object)
 {
   NaTrayManager *manager;
-
+  
   manager = NA_TRAY_MANAGER (object);
 
   na_tray_manager_unmanage (manager);
 
   g_list_free (manager->messages);
   g_hash_table_destroy (manager->socket_table);
-
+  
   G_OBJECT_CLASS (na_tray_manager_parent_class)->finalize (object);
 }
 
@@ -330,7 +325,7 @@ na_tray_manager_handle_message_data (NaTrayManager       *manager,
 {
   GList *p;
   int    len;
-
+  
   /* Try to see if we can find the pending message in the list */
   for (p = manager->messages; p; p = p->next)
     {
@@ -432,7 +427,7 @@ na_tray_manager_handle_cancel_message (NaTrayManager       *manager,
   long       id;
 
   id = xevent->data.l[2];
-
+  
   /* Check if the message is in the queue and remove it if so */
   for (p = manager->messages; p; p = p->next)
     {
@@ -450,7 +445,7 @@ na_tray_manager_handle_cancel_message (NaTrayManager       *manager,
 
   socket = g_hash_table_lookup (manager->socket_table,
                                 GINT_TO_POINTER (xevent->window));
-
+  
   if (socket)
     {
       g_signal_emit (manager, manager_signals[MESSAGE_CANCELLED], 0,
@@ -522,7 +517,7 @@ na_tray_manager_selection_clear_event (GtkWidget         *widget,
   return FALSE;
 }
 #endif
-#endif
+#endif  
 
 static void
 na_tray_manager_unmanage (NaTrayManager *manager)
@@ -542,9 +537,9 @@ na_tray_manager_unmanage (NaTrayManager *manager)
   g_assert (GTK_IS_INVISIBLE (invisible));
   g_assert (gtk_widget_get_realized (invisible));
   g_assert (GDK_IS_WINDOW (window));
-
+  
   display = gtk_widget_get_display (invisible);
-
+  
   if (gdk_selection_owner_get_for_display (display, manager->selection_atom) ==
       window)
     {
@@ -557,7 +552,7 @@ na_tray_manager_unmanage (NaTrayManager *manager)
     }
 
   gdk_window_remove_filter (window,
-                            na_tray_manager_window_filter, manager);
+                            na_tray_manager_window_filter, manager);  
 
   manager->invisible = NULL; /* prior to destroy for reentrancy paranoia */
   gtk_widget_destroy (invisible);
@@ -621,8 +616,7 @@ na_tray_manager_set_visual_property (NaTrayManager *manager)
   visual_atom = gdk_x11_get_xatom_by_name_for_display (display,
 						       "_NET_SYSTEM_TRAY_VISUAL");
 
-  if (gdk_screen_get_rgba_visual (manager->screen) != NULL &&
-      gdk_screen_is_composited (manager->screen))
+  if (gdk_screen_get_rgba_visual (manager->screen) != NULL)
     xvisual = GDK_VISUAL_XVISUAL (gdk_screen_get_rgba_visual (manager->screen));
   else
     {
@@ -644,62 +638,6 @@ na_tray_manager_set_visual_property (NaTrayManager *manager)
 #endif
 }
 
-static void
-na_tray_manager_set_padding_property (NaTrayManager *manager)
-{
-#ifdef GDK_WINDOWING_X11
-  GdkWindow  *window;
-  GdkDisplay *display;
-  Atom        atom;
-  gulong      data[1];
-
-  g_return_if_fail (manager->invisible != NULL);
-  window = gtk_widget_get_window (manager->invisible);
-  g_return_if_fail (window != NULL);
-
-  display = gtk_widget_get_display (manager->invisible);
-  atom = gdk_x11_get_xatom_by_name_for_display (display,
-                                                "_NET_SYSTEM_TRAY_PADDING");
-
-  data[0] = manager->padding;
-
-  XChangeProperty (GDK_DISPLAY_XDISPLAY (display),
-                   GDK_WINDOW_XID (window),
-                   atom,
-                   XA_CARDINAL, 32,
-                   PropModeReplace,
-                   (guchar *) &data, 1);
-#endif
-}
-
-static void
-na_tray_manager_set_icon_size_property (NaTrayManager *manager)
-{
-#ifdef GDK_WINDOWING_X11
-  GdkWindow  *window;
-  GdkDisplay *display;
-  Atom        atom;
-  gulong      data[1];
-
-  g_return_if_fail (manager->invisible != NULL);
-  window = gtk_widget_get_window (manager->invisible);
-  g_return_if_fail (window != NULL);
-
-  display = gtk_widget_get_display (manager->invisible);
-  atom = gdk_x11_get_xatom_by_name_for_display (display,
-                                                "_NET_SYSTEM_TRAY_ICON_SIZE");
-
-  data[0] = manager->icon_size;
-
-  XChangeProperty (GDK_DISPLAY_XDISPLAY (display),
-                   GDK_WINDOW_XID (window),
-                   atom,
-                   XA_CARDINAL, 32,
-                   PropModeReplace,
-                   (guchar *) &data, 1);
-#endif
-}
-
 static void
 na_tray_manager_set_colors_property (NaTrayManager *manager)
 {
@@ -717,18 +655,18 @@ na_tray_manager_set_colors_property (NaTrayManager *manager)
   atom = gdk_x11_get_xatom_by_name_for_display (display,
                                                 "_NET_SYSTEM_TRAY_COLORS");
 
-  data[0] = manager->fg.red * 65535;
-  data[1] = manager->fg.green * 65535;
-  data[2] = manager->fg.blue * 65535;
-  data[3] = manager->error.red * 65535;
-  data[4] = manager->error.green * 65535;
-  data[5] = manager->error.blue * 65535;
-  data[6] = manager->warning.red * 65535;
-  data[7] = manager->warning.green * 65535;
-  data[8] = manager->warning.blue * 65535;
-  data[9] = manager->success.red * 65535;
-  data[10] = manager->success.green * 65535;
-  data[11] = manager->success.blue * 65535;
+  data[0] = manager->fg.red * 0x101;
+  data[1] = manager->fg.green * 0x101;
+  data[2] = manager->fg.blue * 0x101;
+  data[3] = manager->error.red * 0x101;
+  data[4] = manager->error.green * 0x101;
+  data[5] = manager->error.blue * 0x101;
+  data[6] = manager->warning.red * 0x101;
+  data[7] = manager->warning.green * 0x101;
+  data[8] = manager->warning.blue * 0x101;
+  data[9] = manager->success.red * 0x101;
+  data[10] = manager->success.green * 0x101;
+  data[11] = manager->success.blue * 0x101;
 
   XChangeProperty (GDK_DISPLAY_XDISPLAY (display),
                    GDK_WINDOW_XID (window),
@@ -742,16 +680,16 @@ na_tray_manager_set_colors_property (NaTrayManager *manager)
 #ifdef GDK_WINDOWING_X11
 
 static gboolean
-na_tray_manager_manage_screen_x11 (NaTrayManager *manager,
-				   GdkScreen     *screen)
+na_tray_manager_manage_screen_x11 (NaTrayManager *manager)
 {
   GdkDisplay *display;
-  Screen     *xscreen;
-  GtkWidget  *invisible;
-  GdkWindow  *window;
-  char       *selection_atom_name;
-  guint32     timestamp;
-
+  GdkScreen *screen;
+  Screen *xscreen;
+  GtkWidget *invisible;
+  GdkWindow *window;
+  char *selection_atom_name;
+  guint32 timestamp;
+  
   g_return_val_if_fail (NA_IS_TRAY_MANAGER (manager), FALSE);
   g_return_val_if_fail (manager->screen == NULL, FALSE);
 
@@ -759,23 +697,24 @@ na_tray_manager_manage_screen_x11 (NaTrayManager *manager,
    * we can't create another one.
    */
 #if 0
-  if (na_tray_manager_check_running_screen_x11 (screen))
+  if (na_tray_manager_check_running_screen_x11 ())
     return FALSE;
 #endif
-
+  
+  screen = gdk_screen_get_default ();
   manager->screen = screen;
 
   display = gdk_screen_get_display (screen);
   xscreen = GDK_SCREEN_XSCREEN (screen);
-
+  
   invisible = gtk_invisible_new_for_screen (screen);
   gtk_widget_realize (invisible);
-
+  
   gtk_widget_add_events (invisible,
                          GDK_PROPERTY_CHANGE_MASK | GDK_STRUCTURE_MASK);
 
   selection_atom_name = g_strdup_printf ("_NET_SYSTEM_TRAY_S%d",
-					 gdk_x11_screen_get_screen_number (screen));
+                                         gdk_x11_get_default_screen ());
   manager->selection_atom = gdk_atom_intern (selection_atom_name, FALSE);
   g_free (selection_atom_name);
 
@@ -784,10 +723,8 @@ na_tray_manager_manage_screen_x11 (NaTrayManager *manager,
 
   na_tray_manager_set_orientation_property (manager);
   na_tray_manager_set_visual_property (manager);
-  na_tray_manager_set_padding_property (manager);
-  na_tray_manager_set_icon_size_property (manager);
   na_tray_manager_set_colors_property (manager);
-
+  
   window = gtk_widget_get_window (invisible);
 
   timestamp = gdk_x11_get_server_time (window);
@@ -847,7 +784,7 @@ na_tray_manager_manage_screen_x11 (NaTrayManager *manager,
       manager->invisible = NULL;
 
       manager->screen = NULL;
-
+ 
       return FALSE;
     }
 }
@@ -855,14 +792,12 @@ na_tray_manager_manage_screen_x11 (NaTrayManager *manager,
 #endif
 
 gboolean
-na_tray_manager_manage_screen (NaTrayManager *manager,
-			       GdkScreen     *screen)
+na_tray_manager_manage_screen (NaTrayManager *manager)
 {
-  g_return_val_if_fail (GDK_IS_SCREEN (screen), FALSE);
   g_return_val_if_fail (manager->screen == NULL, FALSE);
 
 #ifdef GDK_WINDOWING_X11
-  return na_tray_manager_manage_screen_x11 (manager, screen);
+  return na_tray_manager_manage_screen_x11 (manager);
 #else
   return FALSE;
 #endif
@@ -871,15 +806,17 @@ na_tray_manager_manage_screen (NaTrayManager *manager,
 #ifdef GDK_WINDOWING_X11
 
 static gboolean
-na_tray_manager_check_running_screen_x11 (GdkScreen *screen)
+na_tray_manager_check_running_screen_x11 (void)
 {
   GdkDisplay *display;
-  Atom        selection_atom;
-  char       *selection_atom_name;
+  GdkScreen *screen;
+  Atom selection_atom;
+  char *selection_atom_name;
 
+  screen = gdk_screen_get_default ();
   display = gdk_screen_get_display (screen);
   selection_atom_name = g_strdup_printf ("_NET_SYSTEM_TRAY_S%d",
-                                         gdk_x11_screen_get_screen_number (screen));
+                                         gdk_x11_get_default_screen ());
   selection_atom = gdk_x11_get_xatom_by_name_for_display (display,
                                                           selection_atom_name);
   g_free (selection_atom_name);
@@ -894,12 +831,10 @@ na_tray_manager_check_running_screen_x11 (GdkScreen *screen)
 #endif
 
 gboolean
-na_tray_manager_check_running (GdkScreen *screen)
+na_tray_manager_check_running (void)
 {
-  g_return_val_if_fail (GDK_IS_SCREEN (screen), FALSE);
-
 #ifdef GDK_WINDOWING_X11
-  return na_tray_manager_check_running_screen_x11 (screen);
+  return na_tray_manager_check_running_screen_x11 ();
 #else
   return FALSE;
 #endif
@@ -921,47 +856,19 @@ na_tray_manager_set_orientation (NaTrayManager  *manager,
     }
 }
 
-void
-na_tray_manager_set_padding (NaTrayManager *manager,
-                             gint           padding)
-{
-  g_return_if_fail (NA_IS_TRAY_MANAGER (manager));
-
-  if (manager->padding != padding)
-    {
-      manager->padding = padding;
-
-      na_tray_manager_set_padding_property (manager);
-    }
-}
-
-void
-na_tray_manager_set_icon_size (NaTrayManager *manager,
-                               gint           icon_size)
-{
-  g_return_if_fail (NA_IS_TRAY_MANAGER (manager));
-
-  if (manager->icon_size != icon_size)
-    {
-      manager->icon_size = icon_size;
-
-      na_tray_manager_set_icon_size_property (manager);
-    }
-}
-
 void
 na_tray_manager_set_colors (NaTrayManager *manager,
-                            GdkRGBA       *fg,
-                            GdkRGBA       *error,
-                            GdkRGBA       *warning,
-                            GdkRGBA       *success)
+                            ClutterColor  *fg,
+                            ClutterColor  *error,
+                            ClutterColor  *warning,
+                            ClutterColor  *success)
 {
   g_return_if_fail (NA_IS_TRAY_MANAGER (manager));
 
-  if (!gdk_rgba_equal (&manager->fg, fg) ||
-      !gdk_rgba_equal (&manager->error, error) ||
-      !gdk_rgba_equal (&manager->warning, warning) ||
-      !gdk_rgba_equal (&manager->success, success))
+  if (!clutter_color_equal (&manager->fg, fg) ||
+      !clutter_color_equal (&manager->error, error) ||
+      !clutter_color_equal (&manager->warning, warning) ||
+      !clutter_color_equal (&manager->success, success))
     {
       manager->fg = *fg;
       manager->error = *error;
diff --git a/src/imports/natray/na-tray-manager.h b/src/imports/natray/na-tray-manager.h
index 1fede4ab..727b02d4 100644
--- a/src/imports/natray/na-tray-manager.h
+++ b/src/imports/natray/na-tray-manager.h
@@ -26,6 +26,7 @@
 #include <gdk/gdkx.h>
 #endif
 #include <gtk/gtk.h>
+#include <clutter/clutter.h>
 
 #include "na-tray-child.h"
 
@@ -37,7 +38,7 @@ G_BEGIN_DECLS
 #define NA_IS_TRAY_MANAGER(obj)			(G_TYPE_CHECK_INSTANCE_TYPE ((obj), NA_TYPE_TRAY_MANAGER))
 #define NA_IS_TRAY_MANAGER_CLASS(klass)		(G_TYPE_CHECK_CLASS_TYPE ((klass), NA_TYPE_TRAY_MANAGER))
 #define NA_TRAY_MANAGER_GET_CLASS(obj)		(G_TYPE_INSTANCE_GET_CLASS ((obj), NA_TYPE_TRAY_MANAGER, NaTrayManagerClass))
-
+	
 typedef struct _NaTrayManager	    NaTrayManager;
 typedef struct _NaTrayManagerClass  NaTrayManagerClass;
 
@@ -50,16 +51,14 @@ struct _NaTrayManager
   Atom    opcode_atom;
   Atom    message_data_atom;
 #endif
-
+  
   GtkWidget *invisible;
   GdkScreen *screen;
   GtkOrientation orientation;
-  gint padding;
-  gint icon_size;
-  GdkRGBA fg;
-  GdkRGBA error;
-  GdkRGBA warning;
-  GdkRGBA success;
+  ClutterColor fg;
+  ClutterColor error;
+  ClutterColor warning;
+  ClutterColor success;
 
   GList *messages;
   GHashTable *socket_table;
@@ -79,7 +78,7 @@ struct _NaTrayManagerClass
 			      const gchar        *message,
 			      glong               id,
 			      glong               timeout);
-
+  
   void (* message_cancelled) (NaTrayManager      *manager,
 			      NaTrayChild        *child,
 			      glong               id);
@@ -89,22 +88,17 @@ struct _NaTrayManagerClass
 
 GType           na_tray_manager_get_type        (void);
 
-gboolean        na_tray_manager_check_running   (GdkScreen          *screen);
+gboolean        na_tray_manager_check_running   (void);
 NaTrayManager  *na_tray_manager_new             (void);
-gboolean        na_tray_manager_manage_screen   (NaTrayManager      *manager,
-						 GdkScreen          *screen);
+gboolean        na_tray_manager_manage_screen   (NaTrayManager      *manager);
 void            na_tray_manager_set_orientation (NaTrayManager      *manager,
 						 GtkOrientation      orientation);
 GtkOrientation  na_tray_manager_get_orientation (NaTrayManager      *manager);
-void            na_tray_manager_set_padding     (NaTrayManager      *manager,
-						 gint                padding);
-void            na_tray_manager_set_icon_size   (NaTrayManager      *manager,
-						 gint                padding);
 void            na_tray_manager_set_colors      (NaTrayManager      *manager,
-						 GdkRGBA            *fg,
-						 GdkRGBA            *error,
-						 GdkRGBA            *warning,
-						 GdkRGBA            *success);
+						 ClutterColor       *fg,
+						 ClutterColor       *error,
+						 ClutterColor       *warning,
+						 ClutterColor       *success);
 
 
 G_END_DECLS
```

**Comment by serebit** [comment]
I think a paste/haste/gist would be more appropriate, that diff is pretty long @fossfreedom

**Comment by JoshStrobl** [comment]
@fossfreedom I'm not sure it's significant, I have a lot of that locally already and it didn't make any different in my testing unfortunately. For instance the gdk composite functions were already changed, the size stuff isn't really applicable since we enforce a fixed size anyways (so any minimum isn't really needed), etc.

**Comment by fossfreedom** [comment]
Yeah - think you are right - I've copy-pasted and fiddled to get the whole thing to compile - individual icons no longer have transparent backgrounds. So it appears to be even more broke than it was.

**Comment by chax** [comment]
`budgie-desktop 10.5 (git-a023c7781435d71e463184124a5cc8b26985d961)`
Works for me.

**Comment by ktw** [comment]
Got this problem in the 10.5.1-204 update, on two machines at the same time.

**Comment by JoshStrobl** [comment]
Yes, clearly the patch is working consistently for some and not others. Hence why it is still open.

**Comment by ktw** [comment]
Since the problem is new on my two long running Solus Budgie installations, I figured it had to be something introduced in the newest version.

**Comment by JoshStrobl** [comment]
It isn't, it's been a long standing issue that only got more prominent because of the latest GNOME stack upgrade.

**Comment by Staudey** [comment]
Just a tiny bit of additional information:
This issue occurs pretty much every time I log in and start Riot plus Hexchat. But, after I restart the Budgie panel via `budgie-panel --replace &!`, the issue seems to disappear completely and I can't even force the visual corruption by randomly opening and closing the applications with tray icons.

**Comment by parrishpotato** [comment]
Not sure if this is related or not, but every time I boot into my laptop, the wifi icon looks strange and doesn't show whether I'm connected or not, and if I set the panel to be transparent it still has a black bar around it. However, if I log out and log back in, it seems to fix itself, it only messes up when booting for some reason, hope that helps.

**Comment by Umlatt** [comment]
Removing system-tray applet/reboot/re-add system tray applet seems to have resolved it for me (been running clean for about a week (on my daily driver machine)).

I have been running the machine in question for about 2 years (doing weekly syncs to latest patches).
Looks like, somewhere along the line, during an upgrade, there was a corruption/change to the system tray applet.

Forcing a rebuild off of the latest version seems to have cured it.

**Comment by Xmetalfanx** [comment]
Not sure when i noticed this starting but I had been ignoring it ... before I tried removing the system tray and re-adding it, the problem seems fixed, but say i reboot ... the problem eventually comes up again 
![tray](https://user-images.githubusercontent.com/1390400/81443386-5732ba00-9143-11ea-9541-777ebacee5df.png) the icons toward the left seem to have a background of the icons to the right ....

L->R it's Variety (wallpaper changer), Strawberry, and Hexchat (while i cant tell what it is ... the Hexchat icon has something in the backgronud or something seems off to me) ... the apps work and right clicking where the icon is shows the right "tray menu" so to speak ... it's just the appearance is off

I hope I posted this in the right place as looking over the name and other posts on this issue (got here via the Solus Forums btw) ... it seems related

**Comment by JacekJagosz** [comment]
@serebit Thank you so much, your patches worked and finally the system tray works properly for me.
(Updated Budgie Desktop is in Solus' unstable repos, but as usual it should be synced to stable on friday)

**Comment by serebit** [comment]
I won't lie, @JacekJagosz, fixing issues dating all the way back to 2017 feels *real good*. Glad it worked for you!

**Comment by geckolinux** [comment]
I have been experiencing this issue mainly on my oldest and slowest 2009-era laptop, running the latest Budgie on openSUSE, using the normal `nm-applet`. On newer and faster laptops it doesn't seem to occur much or at all. And I've seen it a few times in VirtualBox and in QEMU/KVM too, but not consistently.

**Comment by JacekJagosz** [comment]
@geckolinux Could you check if the Budgie version OpenSUSE uses is with the new tray or the old one (when was it last updates)?
New implementation fixed all the problems people had, so if SUSE uses old version maybe ask them to update Budgie, and if they use new one give more info here.

**Comment by geckolinux** [comment]
Hi @JacekJagosz thanks for the response.

It is the latest 10.5.1 budgie release, recently packaged by an openSUSE volunteer. You can see the spec files for the RPM package build here:
https://build.opensuse.org/package/show/X11:Solus/budgie-desktop
And here's the full list of package versions that I use to generate ISOs with (for the slightly older openSUSE Leap 15.2 branch and the rolling Tumbleweed release, this bug happens on both branches):
- [Leap-15.2-based.txt](https://github.com/solus-project/budgie-desktop/files/5150293/Leap-15.2-based.txt)
- [Tumbleweed-based.txt](https://github.com/solus-project/budgie-desktop/files/5150294/Tumbleweed-based.txt)

I'm not sure if I understood correctly the history of this bug, but it looks like maybe the actual bug wasn't fixed, but rather a workaround was applied by changing to a different NetworkManager applet? I am using the normal `nm-applet` that Solus used to include, but even after uninstalling that the Parcellite clipboard manager that appears in the system tray also has a corrupted background.

I also confirm that this workaround of killing `budgie-panel` on session startup works:
https://discuss.getsol.us/d/3229-system-tray-applet-glitch-in-budgie/8

**Comment by fossfreedom** [comment]
Yeah - opensuse will need to go back through the commit history and
cherry-pick the half-a-dozen or so patches in this area.  I'm going to-do
the same for UB 20.04 very soon as well.

Don't know why the reluctance to produce a 10.5.2 with this in - oh well a
maintainers life is never easy... :)

**Comment by JacekJagosz** [comment]
(Correct me if I got something wrong)
The error you are encountering was a common issue with the system tray that I was encountering as well.
But fortunately recently serebit rewrote the system tray - his "carbontray" replaced old "na-tray", and that fixed most issues people experienced. That was patch was merged on 3rd of July and as Solus uses newest git version, that problem on Solus was fixed. But as a new release hasn't been tagged yet (10.5.2), SUSE still uses version that doesn't have this patch.
So what you can do is build newest Budgie yourself, ask SUSE maintainer to cherry-pick those patches, or wait for Budgie 10.5.2 release.
Either way, good news is that bug has been fixed and should be fixed on your machine soon™

**Comment by geckolinux** [comment]
Ahh, I see now, so "carbontray" is a new system tray, I thought it was a different NetworkManager tray. Thanks for clearing that up.
Any rough estimation on the how much time is left before the Budgie 10.5.2 release?

**Comment by JoshStrobl** [comment]
> Any rough estimation on the how much time is left before the Budgie 10.5.2 release?

When it's ready. Not giving any ETAs.
