### ISSUE TITLE
Battery Notification Spam

### ISSUE THREAD

**Issue by pitothepowerof3** [solus-project/budgie-desktop#449]
Whenever the battery reaches critical level, and the power manager issues a notification, it creates a new notification each time. Logging out and back in fixes this issue. 
![image](https://cloud.githubusercontent.com/assets/9117849/15454909/bb0f62ca-200a-11e6-87da-9ce5dea9365c.png)

System Info:
![image](https://cloud.githubusercontent.com/assets/9117849/15454942/83e993a0-200b-11e6-8534-9b0965e109c8.png)

**Comment by pitothepowerof3** [comment]
Not entirely sure if this is on the battery manager end or the WM end, but I put it here. Feel free to move it/whatever as needed.

**Comment by ikeydoherty** [comment]
Fixed in commit above ^ Will be rolled out in the next release

**Comment by garnieretienne** [comment]
I think I still have this problem. When my battery is critical, the notification appears maybe 6~8 times at once (with the sound chaining: *ting* *ting* *ting*...). 

It's not a critical bug but append to me the two times my battery was low (I'm new to Solus).
