### ISSUE TITLE
Battery indicator gives wrong information

### ISSUE THREAD

**Issue by GrisuProjects** [solus-project/budgie-desktop#479]
As the title says the battery indicator/applet does display the wrong battery information. But GNOME control center displays the right one.

![screenshot from 2016-06-23 18-00-44](https://cloud.githubusercontent.com/assets/15364860/16310474/eec9d228-396c-11e6-9d83-daffab0e7812.png)

Also when I plug in my laptop, the applet does not update properly. Again, it works in GNOME control center and also did work correctly under Solus 1.1. So maybe it is an 1.2 issue

![screenshot from 2016-06-23 18-06-29](https://cloud.githubusercontent.com/assets/15364860/16310613/83107c48-396d-11e6-8e81-69bb2e140ed3.png)

**Comment by ikeydoherty** [comment]
Known issue atm

**Comment by ikeydoherty** [comment]
Fixed in git, update is in the Solus 1.2 repos for this

**Comment by TheMonDon** [comment]
I still have this problem when coming out of standby, and leaving my laptop plugged in. It does fix it-self when logging out and back in, though.
